import {styled} from 'stitches.config'
import Box from '@/design-system/primitives/Box'
import Head from 'next/head'
import { ReactNode} from 'react'
import Input from '@/design-system/primitives/Input'
import Profile from '@/design-system/Profile'

const StyledMain = styled('main', {
    backgroundColor: '$background',
    height: 'auto',
    boxSizing: 'border-box',
    overflowY: 'scroll',
    minHeight: '88vh',
    overflowX: 'hidden',
    padding: '$2 $4',
    paddingTop: '$5',
    display: 'flex',
    flex: '1',
    flexDirection: 'row',
    gap: '$5'
})

const StyledFooter = styled('footer', {
    padding: '$1 $2',
    backgroundColor: '$foreground',
    borderRadius: '$2 $2 0 0',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
})

const StyledHeader = styled('header', {
    position: 'sticky',
    backgroundColor: '$background',
    padding: '$2 $4',
    color: '$text',
    overflow: 'hidden',
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center'
})

type Props = {
    children?: ReactNode;
}

const Layout = ({children}:Props) =>{
    return(
            <Box>
                <Head>
                    <title>Boardroom Governance</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <StyledHeader>
                    <Box layout='flexBoxRow' css={{gap:'$0', alignItems:'center'}}>
                        <Profile/>
                        <p>Boardroom Governance</p>
                    </Box>
                    <Box>
                        <Input css={{ minWidth:'256px' }} type='search' placeholder="search" />
                    </Box>
                </StyledHeader>
                <StyledMain>
                    {children}
                </StyledMain>
                <StyledFooter>
                </StyledFooter>
            </Box>
    )
}

export default Layout